- - 2.2.7 엑셀 read, write

In [1]:
import openpyxl

wb=openpyxl.load_workbook('sample.xlsx')
sheet=wb['Sheet1']
print(sheet.max_column, sheet.max_row)
print(sheet.cell(row=1, column=1).value)
print(sheet.cell(row=2, column=1).value)

wb.close()

3 6
이름
Kei


In [4]:
wb=openpyxl.load_workbook('sample.xlsx')
sheet=wb['Sheet1']

for row in sheet.iter_rows(min_row=2):
    for cell in row:
        print(cell.value)
    print('-'*10)
    
wb.close()

Kei
35
1234-1234
----------
Hong
26
4320-1420
----------
Kim
41
1234-5678
----------
Choi
38
4023-3411
----------
Go
27
1469-4023
----------


In [5]:
wb=openpyxl.load_workbook('sample.xlsx')
sheet=wb['Sheet1']

cells=sheet['A2':'C3']

for row in cells:
    for cell in row:
        print(cell.value)
    print('-'*10)
    
wb.close()

Kei
35
1234-1234
----------
Hong
26
4320-1420
----------


OpenPyXL로 엑셀 파일 write

In [6]:
wb=openpyxl.Workbook()
sheet=wb.active
sheet.title='회원정보'
header_titles=['이름','전화번호']

for idx, title in enumerate(header_titles):
    sheet.cell(row=1, column=idx+1, value=title)
    
members=[('ket','010-1234-1234'), ('hong', '010-4321-1234')]

row_num=2 # 2행부터 데이터

for r, member in enumerate(members): # 회원 정보
    for c,v in enumerate(member): # 인덱스 (이름, 전번)
        sheet.cell(row=row_num+r, column=c+1, value=v) # 인덱스가 0부터 시작하기 때문에 각각 +1
        
wb.save('members.xlsx')
wb.close()

---

# 2.3 데이터 분석을 위한 필수 라이브러리

## 2.3.1 넘파이

In [8]:
import numpy as np

arr=np.array([1,2,3])
print(arr,type(arr))

[1 2 3] <class 'numpy.ndarray'>


In [9]:
matrix=np.array([ [1,2,3], [4,5,6]])
print(matrix)

[[1 2 3]
 [4 5 6]]


In [10]:
A=np.array([ [1,2], [3,4]])
B=np.array([ [1,1], [1,1]])
print(A+B)

[[2 3]
 [4 5]]
